// <auto-generated />
namespace Restaurants.DBModel.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class Suburb_PostCode : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Suburb_PostCode));
        
        string IMigrationMetadata.Id
        {
            get { return "201610280317347_Suburb_PostCode"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
